site_name: Computing on Encrypted Data
theme:
  name: material
  logo: "assets/fhe.svg"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - autorefs

nav:
    - Home: 'index.md'
    - 'Tensor Based Schemes':
        - 'FHE from Tensor Products' : 'bgv/fhe-from-tensoring.md'
        - 'BGV': 'bgv/bgv.md'
        - 'BFV': 'bgv/bfv.md'
        - 'CKKS' : 'bgv/ckks.md'
    - 'NTRU Based Schemes':
        - 'NTRU' : 'NTRU/fhe-from-NTRU.md'
    - 'Eigenvalue Based Schemes':
        - 'FHE from Eigenvalues' : 'gsw/eigenvalue.md'
        - 'GSW' : 'gsw/gsw.md'
        - 'FHWE' : 'gsw/fhew.md'
        - 'TFHE' : 'gsw/tfhe.md'
    - 'Complexity Assumptions':
        - 'SVP to LWE Reduction' : 'appendix/svp2lwe.md'
    - 'Optimization Techniques':
        - 'NTT optimization' : 'appendix/ntt.md'
        - 'SIMD Operations' : 'appendix/simd.md'
    - About:
        - 'License': 'license.md'
